parameters:
    pxCore.wordToPdf.service.class: pxCore\WordToPdfBundle\Services\WordToPdfService
    libreoffice: /usr/bin/libreoffice
services:
    pxCore_wordToPdf_service:
        class: %pxCore.wordToPdf.service.class%
        arguments: ['@service_container']
